!----------------------------------------------------------------------------------!
!    Copyright (c) 2010-2018 Pauli Parkkinen, Eelis Solala, Wen-Hua Xu,            !
!                            Sergio Losilla, Elias Toivanen, Jonas Juselius        !
!                                                                                  !
!    Permission is hereby granted, free of charge, to any person obtaining a copy  !
!    of this software and associated documentation files (the "Software"), to deal !
!    in the Software without restriction, including without limitation the rights  !
!    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell     !
!    copies of the Software, and to permit persons to whom the Software is         !
!    furnished to do so, subject to the following conditions:                      !
!                                                                                  !
!    The above copyright notice and this permission notice shall be included in all!
!    copies or substantial portions of the Software.                               !
!                                                                                  !
!    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    !
!    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,      !
!    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE   !
!    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER        !
!    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, !
!    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE !
!    SOFTWARE.                                                                     !
!----------------------------------------------------------------------------------!
!----------------------------------------------------------------------------------!
!    NOTE: This file is automatically generated by the python program              !
!    'generate objects.py'. DO NOT MODIFY THIS FILE manually. To change            !
!    the contents of this file, edit the input_parameters.xml file and run         !
!    'python generate_objects.py' in the 'python/' folder.                         !
!----------------------------------------------------------------------------------!
module Action_class
    use globals_m
    use ISO_FORTRAN_ENV
    implicit none

    public :: Action

    type   :: Action
        integer                   :: structure_id = 0
        integer                   :: scf_energetics_id = 0
        integer                   :: settings_id = 0
        integer                   :: name = 0
        !> Resume to previous execution by reading in the orbitals etc. if possible 
        !! 
        logical              :: resume = .TRUE.
        !> The interval of mid-storing of orbitals as number of iterations. (0: no 
        !! mid-execution storage) 
        integer                   :: intermediate_orbital_store_interval = 0
        !> Store the result orbitals and other functions. 
        integer                   :: store_result_functions = 0
        !> The path to the folder where the input files (orbitals etc) are stored 
        !! to. 
        character*256              :: input_folder = "./"
        !> The path to the folder where the output files are stored to. 
        character*256              :: output_folder = "./"

    end type

    integer, parameter :: ACTION_OPTIMIZE_ELECTRON_STRUCTURE = 1
    integer, parameter :: ACTION_INPUT_OUTPUT_TEST = 101
    integer, parameter :: DO_NOT_STORE_RESULT_FUNCTIONS = 0
    integer, parameter :: STORE_RESULT_FUNCTIONS = 1
    integer, parameter :: STORE_ONLY_BUBBLES = 2
    integer, parameter :: STORE_ONLY_CUBES = 3

end module
