!----------------------------------------------------------------------------------!
!    Copyright (c) 2010-2018 Pauli Parkkinen, Eelis Solala, Wen-Hua Xu,            !
!                            Sergio Losilla, Elias Toivanen, Jonas Juselius        !
!                                                                                  !
!    Permission is hereby granted, free of charge, to any person obtaining a copy  !
!    of this software and associated documentation files (the "Software"), to deal !
!    in the Software without restriction, including without limitation the rights  !
!    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell     !
!    copies of the Software, and to permit persons to whom the Software is         !
!    furnished to do so, subject to the following conditions:                      !
!                                                                                  !
!    The above copyright notice and this permission notice shall be included in all!
!    copies or substantial portions of the Software.                               !
!                                                                                  !
!    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    !
!    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,      !
!    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE   !
!    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER        !
!    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, !
!    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE !
!    SOFTWARE.                                                                     !
!----------------------------------------------------------------------------------!
!    NOTE: This file is automatically generated by the python program              !
!    'generate_objects.py'. DO NOT MODIFY THIS FILE manually. To change            !
!    the contents of this file, edit the input_parameters.xml file and run         !
!    'python generate_objects.py' in the 'python/' folder.                         !
!----------------------------------------------------------------------------------!
module Settings_class
    use globals_m
    use ISO_FORTRAN_ENV
    implicit none

    public :: ProgramSettings

    !> Type containing settings related to the Function3D objects 
    type :: Function3DSettings 
        !> Number of cells used in the Bubbles objects (Note: the number is scaled 
        !! with corresponding atom charge) 
        integer                   :: bubble_cell_count = 6000
        !> Maximum angular momentum quantum number l used in Bubbles objects. 
        integer                   :: bubble_lmax = 3
        !> The radius from bubbles centers, where the Bubbles ends. 
        real(REAL64)              :: bubble_cutoff_radius = 20.0000000000d0
        !> The spacing between grid points in cube in atomic units (a0). Note: the 
        !! actual number is scaled to fit other parameter values. 
        real(REAL64)              :: cube_grid_spacing = 0.0500000000d0
        !> The radius from atoms centers, where the cube ends. 
        real(REAL64)              :: cube_cutoff_radius = 7.0000000000d0
        !> The offset of bubbles from the center of the cube. This offset is given 
        !! as cube grid points in x, y and z directions. 
        real(REAL64), allocatable :: bubbles_center_offset(:)
        !> Number of Lagrange interpolation polynomials used in Cube grid. 
        integer                   :: bubbles_nlip = 7
        !> Number of Lagrange interpolation polynomials used in Bubbles grids. 
        integer                   :: cube_nlip = 7
        !> grid type in cells of the bubbles. 
        integer                   :: bubbles_grid_type = 1
        !> grid type in cells of the cube. 
        integer                   :: cube_grid_type = 1
        !> Maximum derivate order used in creating the cross terms in Function3D multiplication 
        !! 
        integer                   :: taylor_order = 2
    end type

    !> Type containing settings related to the Gaussian Quadrature objects used 
    !! in Coulomb and Helmholtz operators 
    type :: QuadratureSettings 
        !> Number of linear parameters used in gaussian quadrature. 
        integer                   :: nlin = 20
        !> Number of logarithmic parameters used in gaussian quadrature. 
        integer                   :: nlog = 16
        !> t-start value 
        real(REAL64)              :: tstart = 0.0000000000d0
        !> t-lin value 
        real(REAL64)              :: tlin = 2.0000000000d0
        !> t-log value 
        real(REAL64)              :: tlog = 500.0000000000d0
    end type

    !> Type containing settings related to the Coulomb operator 
    type :: Coulomb3DSettings 
        !> Is the used coulomb operator based on Grid Based Fast Multipole Method 
        !! 
        logical              :: gbfmm = .TRUE.
        !> Maximum angular momentum quantum number l value for the multipole evaluation. 
        !! Increasing this number will increase the accuracy of the farfield potential 
        !! evaluation. 
        integer                   :: farfield_potential_input_lmax = 12
    end type

    !> Type containing settings related to the Helmholtz operator 
    type :: Helmholtz3DSettings 
        !> Is the used helmholtz operator based on Grid Based Fast Multipole Method 
        !! 
        logical              :: gbfmm = .TRUE.
        !> Maximum angular momentum quantum number l value for the multipole evaluation. 
        !! Increasing this number will increase the accuracy of the farfield potential 
        !! evaluation. 
        integer                   :: farfield_potential_input_lmax = 22
        !> Maximum angular momentum quantum number l value for the potential evaluation. 
        !! Increasing this number will increase the accuracy of the farfield potential 
        !! evaluation. 
        integer                   :: farfield_potential_lmax = 22
        !> If the evaluation of farfield potential will be made using with no multipole 
        !! to local expansion conversions. Using this setting will increase the execution 
        !! time. Should be used only for debugging purposes. 
        logical              :: multipole_evaluation = .FALSE.
    end type

    !> Type containing settings related to the quantum dot simulations. 
    type :: QuantumDotSettings 
        !> Effective mass of electron in the x-direction. 
        real(REAL64)              :: electron_effective_mass_x = 1.0000000000d0
        !> Effective mass of electron in the y-direction. 
        real(REAL64)              :: electron_effective_mass_y = 1.0000000000d0
        !> Effective mass of electron in the z-direction. 
        real(REAL64)              :: electron_effective_mass_z = 1.0000000000d0
        !> Effective mass of hole in the x-direction. 
        real(REAL64)              :: hole_effective_mass_x = 1.0000000000d0
        !> Effective mass of hole in the y-direction. 
        real(REAL64)              :: hole_effective_mass_y = 1.0000000000d0
        !> Effective mass of hole in the z-direction. 
        real(REAL64)              :: hole_effective_mass_z = 1.0000000000d0
        !> Electronic constant. 
        real(REAL64)              :: electronic_constant = 1.0000000000d0
        !> Relative electron diffraction constant. 
        real(REAL64)              :: relative_electron_diffraction_constant = 1.0000000000d0
    end type

    !> Type containing settings related to the SCF loop 
    type :: SCFSettings 
        !> Type of the ab initio calculation 
        integer                   :: method = 1
        !> Determines the type of SCF loop: LCMO or Helmholtz-SCF. 
        integer                   :: type = 1
        !> The weight with which the update is applied. 
        real(REAL64)              :: update_weight = 1.0000000000d0
        !> Determines if the calculation is restricted to singlet electronic configurations. 
        !! 
        logical              :: restricted = .TRUE.
    end type

    integer, parameter :: SCF_METHOD_HARTREE_FOCK = 1
    integer, parameter :: SCF_METHOD_DFT = 2
    integer, parameter :: SCF_TYPE_HELMHOLTZ = 1
    integer, parameter :: SCF_TYPE_LCMO = 2

    !> Type containing settings specifically related to the Hartree-Fock. 
    type :: HFSettings 
        !> The f-parameter used for the open shells in the Restricted Open-Shell Hartree 
        !! Fock calculations. 
        real(REAL64)              :: rohf_f = 0.5000000000d0
        !> The a-parameter used for the open shells in the Restricted Open-Shell Hartree 
        !! Fock calculations. 
        real(REAL64)              :: rohf_a = 0.0000000000d0
        !> The b-parameter used for the open shells in the Restricted Open-Shell Hartree 
        !! Fock calculations. 
        real(REAL64)              :: rohf_b = 0.0000000000d0
    end type

    !> Type containing settings related to the DFT and exchange and correlation. 
    !! 
    type :: DFTSettings 
        !> Type of the exchange functional 
        integer                   :: exchange_type = 1
        !> Type of the correlation functional 
        integer                   :: correlation_type = 12
        !> method to update xc object 
        integer                   :: xc_update_method = 0
        !> lmax for exc, vxc 
        integer                   :: xc_lmax = 0
        !> Determines if the electron density and its gradient are (re-)evaluated 
        !! from molecular orbitals. Using this setting makes the calculation more 
        !! accurate but slows it down a bit. 
        logical              :: orbitals_density_evaluation = .FALSE.
    end type

    !> Type containing settings related to the SCF optimizer 
    type :: SCFOptimizerSettings 
        integer                   :: optimizer_type = 1
        !> The maximum number of scf-loop iterations. 
        integer                   :: maximum_iterations = 50
        !> Maximum error allowed for the total energy to achieve SCF-convergence. 
        !! 
        real(REAL64)              :: total_energy_convergence_threshold = 0.0000000100d0
        !> Maximum error allowed for each eigenvalue to achieve SCF-convergence. 
        real(REAL64)              :: eigenvalue_convergence_threshold = 0.0000100000d0
        !> Number of iterations stored in memory. This parameter only affects to optimizers 
        !! taking advantage of iteration history, like DIIS and KAIN. 
        integer                   :: stored_iteration_count = 4
        !> Number of iterations needed to before the optimization method of the optimizer 
        !! is used. Before this, the power method is used. 
        integer                   :: initialization_iteration_count = 1
        !> Maximum error for the optimization method of the optimizer is used. If 
        !! this threshold has not been breached, the power method is used. 
        real(REAL64)              :: initialization_threshold = 0.1000000000d0
    end type

    integer, parameter :: SCF_OPTIMIZER_TYPE_POWER_METHOD = 1
    integer, parameter :: SCF_OPTIMIZER_TYPE_POWER_KAIN = 2

    !> Type containing settings related to the Configuration Interaction 
    type :: CISettings 
        !> Determines if CI-contribution to energy is evaluated. 
        logical              :: evaluate_ci = .FALSE.
        !> Determines if single-excitations are included in the calculation. 
        logical              :: singles = .TRUE.
        !> Determines if double-excitations are included in the calculation. 
        logical              :: doubles = .TRUE.
        !> Determines if triple-excitations are included in the calculation. 
        logical              :: triples = .FALSE.
        !> Determines if quadruple-excitations are included in the calculation. 
        logical              :: quadruples = .FALSE.
    end type

    !> Type containing all the settings related to functionalities. 
    type :: ProgramSettings 
        type(Function3DSettings)        ::  function3d_settings
        type(QuadratureSettings)        ::  quadrature_settings
        type(Coulomb3DSettings)         ::  coulomb3d_settings
        type(Helmholtz3DSettings)       ::  helmholtz3d_settings
        type(QuantumDotSettings)        ::  qd_settings
        type(SCFSettings)               ::  scf_settings
        type(HFSettings)                ::  hf_settings
        type(DFTSettings)               ::  dft_settings
        type(SCFOptimizerSettings)      ::  scfoptimizer_settings
        type(CISettings)                ::  ci_settings
    end type
end module
